var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,d){a.raw=d;return a};$jscomp.arrayIteratorImpl=function(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var d="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(d)return d.call(a);if("number"==typeof a.length)return $jscomp.arrayIterator(a);throw Error(String(a)+" is not an iterable or ArrayLike");};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,f){if(a==Array.prototype||a==Object.prototype)return a;a[d]=f.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<a.length;++d){var f=a[d];if(f&&f.Math==Math)return f}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,d,f){if(!f||null!=a){f=$jscomp.propertyToPolyfillSymbol[d];if(null==f)return a[d];f=a[f];return void 0!==f?f:a[d]}};
$jscomp.polyfill=function(a,d,f,l){d&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,d,f,l):$jscomp.polyfillUnisolated(a,d,f,l))};$jscomp.polyfillUnisolated=function(a,d,f,l){f=$jscomp.global;a=a.split(".");for(l=0;l<a.length-1;l++){var t=a[l];if(!(t in f))return;f=f[t]}a=a[a.length-1];l=f[a];d=d(l);d!=l&&null!=d&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:d})};
$jscomp.polyfillIsolated=function(a,d,f,l){var t=a.split(".");a=1===t.length;l=t[0];l=!a&&l in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var C=0;C<t.length-1;C++){var D=t[C];if(!(D in l))return;l=l[D]}t=t[t.length-1];f=$jscomp.IS_SYMBOL_NATIVE&&"es6"===f?l[t]:null;d=d(f);null!=d&&(a?$jscomp.defineProperty($jscomp.polyfills,t,{configurable:!0,writable:!0,value:d}):d!==f&&(void 0===$jscomp.propertyToPolyfillSymbol[t]&&(f=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[t]=$jscomp.IS_SYMBOL_NATIVE?
    $jscomp.global.Symbol(t):$jscomp.POLYFILL_PREFIX+f+"$"+t),$jscomp.defineProperty(l,$jscomp.propertyToPolyfillSymbol[t],{configurable:!0,writable:!0,value:d})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},d={};try{return d.__proto__=a,d.a}catch(f){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,d){a.__proto__=d;if(a.__proto__!==d)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,d){this.nextAddress=d;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,d){var f=$jscomp.makeIterator(a),l=f.next();$jscomp.generator.ensureIteratorResultIsObject_(l);if(l.done)this.yieldResult=l.value,this.nextAddress=d;else return this.yieldAllIterator_=f,this.yield(l.value,d)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,d){this.catchAddress_=a;void 0!=d&&(this.finallyAddress_=d)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,d){this.nextAddress=a;this.catchAddress_=d||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,d,f){f?this.finallyContexts_[f]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=d||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,d){var f=this.finallyContexts_.splice(d||0)[0];if(f=this.abruptCompletion_=this.abruptCompletion_||f){if(f.isException)return this.jumpToErrorHandler_();void 0!=f.jumpTo&&this.finallyAddress_<f.jumpTo?(this.nextAddress=f.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var d in a)this.properties_.push(d);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var d=this.context_.yieldAllIterator_;if(d)return this.yieldAllStep_("return"in d?d["return"]:function(f){return{value:f,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,d,f){try{var l=a.call(this.context_.yieldAllIterator_,d);$jscomp.generator.ensureIteratorResultIsObject_(l);if(!l.done)return this.context_.stop_(),l;var t=l.value}catch(C){return this.context_.yieldAllIterator_=null,this.context_.throw_(C),this.nextStep_()}this.context_.yieldAllIterator_=null;f.call(this.context_,t);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(d){this.context_.yieldResult=void 0,this.context_.throw_(d)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(d){return a.next_(d)};this["throw"]=function(d){return a.throw_(d)};this["return"]=function(d){return a.return_(d)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,d){var f=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(d));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(f,a.prototype);return f};
$jscomp.asyncExecutePromiseGenerator=function(a){function d(l){return a.next(l)}function f(l){return a["throw"](l)}return new Promise(function(l,t){function C(D){D.done?l(D.value):Promise.resolve(D.value).then(d,f).then(C,t)}C(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
document.addEventListener("DOMContentLoaded",function(){var a,d,f=!1,l=function(b){var c=function(e){return Array.from(e).reduce(function(m,h){return m+h.offsetWidth},0)};b&&(b=c(document.querySelector("#blog-info > a").children),c=c(document.getElementById("menus").children),a=b+c,d=document.getElementById("nav"));d.classList.toggle("hide-menu",768>=window.innerWidth||a>d.offsetWidth-120)},t={open:function(){btf.sidebarPaddingR();document.body.style.overflow="hidden";btf.animateIn(document.getElementById("menu-mask"),
            "to_show 0.5s");document.getElementById("sidebar-menus").classList.add("open");f=!0},close:function(){var b=document.body;b.style.overflow="";b.style.paddingRight="";btf.animateOut(document.getElementById("menu-mask"),"to_hide 0.5s");document.getElementById("sidebar-menus").classList.remove("open");f=!1}},C=function(){var b=function(){btf.scrollToDest(document.getElementById("content-inner").offsetTop,300)},c=document.getElementById("scroll-down");c&&btf.addEventListenerPjax(c,"click",b)},D=function(){var b=
        GLOBAL_CONFIG.highlight;if(b){var c=b.highlightCopy,e=b.highlightLang,m=b.highlightHeightLimit;b=b.plugin;var h=GLOBAL_CONFIG_SITE.isHighlightShrink,n=c||e||void 0!==h,g="highlight.js"===b?document.querySelectorAll("figure.highlight"):document.querySelectorAll('pre[class*="language-"]');if((n||m)&&g.length){var x="prismjs"===b,w=!0===h?"closed":"",y=void 0!==h?'<i class="fas fa-angle-down expand"></i>':"",z=c?'<div class="copy-notice"></div><i class="fas fa-paste copy-button"></i>':"",A=function(k,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             q){if(void 0!==GLOBAL_CONFIG.Snackbar)btf.snackbarShow(q);else{var r=k.previousElementSibling;r.textContent=q;r.style.opacity=1;setTimeout(function(){r.style.opacity=0},800)}},v=function(k){k=k.target.classList;if(k.contains("expand"))this.classList.toggle("closed");else if(k.contains("copy-button")){k=this.parentNode;k.classList.add("copy-true");var q=window.getSelection(),r=document.createRange();r.selectNodeContents(k.querySelectorAll(x?"pre code":"table .code pre")[0]);q.removeAllRanges();q.addRange(r);
        r=this.lastChild;document.queryCommandSupported&&document.queryCommandSupported("copy")?(document.execCommand("copy"),A(r,GLOBAL_CONFIG.copy.success)):A(r,GLOBAL_CONFIG.copy.noSupport);q.removeAllRanges();k.classList.remove("copy-true")}},p=function(){this.classList.toggle("expand-done")},u=function(k,q,r){var B=document.createDocumentFragment();if(n){var E=document.createElement("div");E.className="highlight-tools "+w;E.innerHTML=y+k+z;btf.addEventListenerPjax(E,"click",v);B.appendChild(E)}m&&q.offsetHeight>
    m+30&&(k=document.createElement("div"),k.className="code-expand-btn",k.innerHTML='<i class="fas fa-angle-double-down"></i>',btf.addEventListenerPjax(k,"click",p),B.appendChild(k));"hl"===r?q.insertBefore(B,q.firstChild):q.parentNode.insertBefore(B,q)};x?g.forEach(function(k){if(e){var q='<div class="code-lang">'+(k.getAttribute("data-language")||"Code")+"</div>";btf.wrap(k,"figure",{"class":"highlight"});u(q,k)}else btf.wrap(k,"figure",{"class":"highlight"}),u("",k)}):g.forEach(function(k){if(e){var q=
        k.getAttribute("class").split(" ")[1];if("plain"===q||void 0===q)q="Code";u('<div class="code-lang">'+q+"</div>",k,"hl")}else u("",k,"hl")})}}},K=function(){document.querySelectorAll("#article-container img").forEach(function(b){var c=b.title||b.alt;if(c){var e=document.createElement("div");e.className="img-alt is-center";e.textContent=c;b.insertAdjacentElement("afterend",e)}})},L=function(b){var c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){return 1==e.nextAddress?e.yield(fetch(b),
        2):3!=e.nextAddress?(c=e.yieldResult,e.yield(c.json(),3)):e["return"](e.yieldResult)})},M=function(b,c,e,m){e=void 0===e?!1:e;var h=c.length,n=new InfiniteGrid.JustifiedInfiniteGrid(b,{gap:5,isConstantSize:!0,sizeRange:[150,600],useResizeObserver:!0,observeChildren:!0,useTransform:!0});m&&btf.addGlobalFn("igOfTabs",function(){n.destroy()},!1,m);var g=function(v,p){for(var u=[],k=(v-1)*p,q=0;q<p;++q){var r=k+q;if(r>=h)break;r=c[r];var B=r.alt?'alt="'+r.alt.replace(/"/g,"&quot;")+'"':"",E=r.title?'title="'+
        r.title.replace(/"/g,"&quot;")+'"':"";u.push('<div class="item ">\n            <img src="'+r.url+'" data-grid-maintained-target="true" '+(B+E)+" />\n          </div>")}return u},x=GLOBAL_CONFIG.infinitegrid.buttonText,w=function(v){var p=document.createElement("button");p.textContent=x;var u=function(k){k.target.removeEventListener("click",u);k.target.remove();btf.setLoading.add(v);k=n.getGroups().length+1;n.append(g(k,10),k)};p.addEventListener("click",u);v.insertAdjacentElement("afterend",p)},y=
        Math.ceil(h/10),z=function(v){var p=v.isResize,u=v.mounted;v.updated.length&&u.length&&!p&&(btf.loadLightbox(b.querySelectorAll("img:not(.medium-zoom-image)")),n.getGroups().length===y?(btf.setLoading.remove(b),n.off("renderComplete",z)):e&&(btf.setLoading.remove(b),w(b)))},A=btf.debounce(function(v){v=(+v.groupKey||0)+1;n.append(g(v,10),v);v===y&&n.off("requestAppend",A)},300);btf.setLoading.add(b);n.on("renderComplete",z);e?n.append(g(1,10),1):(n.on("requestAppend",A),n.renderItems());btf.addGlobalFn("justifiedGallery",
        function(){n.destroy()})},F=function(b,c){c=void 0===c?!1:c;var e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(m){if(1==m.nextAddress)return e=function(){var h,n,g,x,w,y,z,A,v;return $jscomp.asyncExecutePromiseGeneratorProgram(function(p){switch(p.nextAddress){case 1:h=$jscomp.makeIterator(b),n=h.next();case 2:if(n.done){p.jumpTo(0);break}g=n.value;if(btf.isHidden(g)){p.jumpTo(3);break}c&&g.classList.contains("loaded")&&(g.querySelector(".gallery-items").innerHTML="",x=g.querySelector(":scope > button"),
        w=g.querySelector(":scope > .loading-container"),x&&x.remove(),w&&w.remove());y="true"===g.getAttribute("data-button");z=g.firstElementChild.textContent;g.classList.add("loaded");if("url"!==g.getAttribute("data-type")){A=JSON.parse(z);p.jumpTo(5);break}return p.yield(L(z),6);case 6:A=p.yieldResult;case 5:v=A,M(g.lastElementChild,v,y,c);case 3:n=h.next(),p.jumpTo(2)}})},"function"===typeof InfiniteGrid?(e(),m.jumpTo(0)):m.yield(getScript(""+GLOBAL_CONFIG.infinitegrid.js),3);e();m.jumpToEnd()})},N=
        function(){var b=document.getElementById("rightside"),c=window.innerHeight+56,e=0,m=document.getElementById("page-header"),h="undefined"!==typeof chatBtn,n=GLOBAL_CONFIG.percent.rightside;if(document.body.scrollHeight<=c)b.classList.add("rightside-show");else{var g="",x=btf.throttle(function(){var w=window.scrollY||document.documentElement.scrollTop,y=w>e;e=w;56<w?(""===g&&(m.classList.add("nav-fixed"),b.classList.add("rightside-show")),y?"down"!==g&&(m.classList.remove("nav-visible"),h&&window.chatBtn.hide(),
            g="down"):"up"!==g&&(m.classList.add("nav-visible"),h&&window.chatBtn.show(),g="up")):(g="",0===w&&m.classList.remove("nav-fixed","nav-visible"),b.classList.remove("rightside-show"));n&&(w=btf.getScrollPercent(w,document.body),y=document.getElementById("go-up"),95>w?(y.classList.add("show-percent"),y.querySelector(".scroll-percent").textContent=w):y.classList.remove("show-percent"));document.body.scrollHeight<=c&&b.classList.add("rightside-show")},300);btf.addEventListenerPjax(window,"scroll",x,{passive:!0})}},
    O=function(){var b=GLOBAL_CONFIG_SITE.isToc,c=GLOBAL_CONFIG.isAnchor,e=document.getElementById("article-container");if(e&&(b||c)){if(b){var m=document.getElementById("card-toc");var h=m.querySelector(".toc-content");var n=h.querySelectorAll(".toc-link");var g=m.querySelector(".toc-percentage");var x=h.classList.contains("is-expand");btf.addEventListenerPjax(h,"click",function(p){var u=p.target.closest(".toc-link");u&&(p.preventDefault(),btf.scrollToDest(btf.getEleTop(document.getElementById(decodeURI(u.getAttribute("href")).replace("#",
        ""))),300),900>window.innerWidth&&m.classList.remove("open"))});var w=function(p){p=p.getBoundingClientRect().top;var u=h.scrollTop;p>document.documentElement.clientHeight-100&&(h.scrollTop=u+150);100>p&&(h.scrollTop=u-150)}}var y=e.querySelectorAll("h1,h2,h3,h4,h5,h6"),z="",A=function(p){if(0===p)return!1;var u="",k="";y.forEach(function(B,E){if(p>btf.getEleTop(B)-80){var H=B.id;u=H?"#"+encodeURI(H):"";k=E}});if(z!==k&&(c&&btf.updateAnchor(u),z=k,b&&(h.querySelectorAll(".active").forEach(function(B){B.classList.remove("active")}),
    ""!==u))){var q=n[k];q.classList.add("active");setTimeout(function(){w(q)},0);if(!x)for(var r=q.parentNode;!r.matches(".toc");r=r.parentNode)r.matches("li")&&r.classList.add("active")}},v=btf.throttle(function(){var p=window.scrollY||document.documentElement.scrollTop;b&&GLOBAL_CONFIG.percent.toc&&(g.textContent=btf.getScrollPercent(p,e));A(p)},100);btf.addEventListenerPjax(window,"scroll",v,{passive:!0})}},G=function(b){var c=(window.globalFn||{}).themeChange||{};Object.keys(c).forEach(function(e){var m=
        c[e];["disqus","disqusjs"].includes(e)?setTimeout(function(){return m(b)},300):m(b)})},I={readmode:function(){var b=document.body;b.classList.add("read-mode");var c=document.createElement("button");c.type="button";c.className="fas fa-sign-out-alt exit-readmode";b.appendChild(c);var e=function(){b.classList.remove("read-mode");c.remove();c.removeEventListener("click",e)};c.addEventListener("click",e)},darkmode:function(){var b="dark"===document.documentElement.getAttribute("data-theme")?"light":"dark";
            "dark"===b?(activateDarkMode(),void 0!==GLOBAL_CONFIG.Snackbar&&btf.snackbarShow(GLOBAL_CONFIG.Snackbar.day_to_night)):(activateLightMode(),void 0!==GLOBAL_CONFIG.Snackbar&&btf.snackbarShow(GLOBAL_CONFIG.Snackbar.night_to_day));saveToLocal.set("theme",b,2);G(b)},"rightside-config":function(b){var c=b.firstElementChild;c.classList.contains("show")&&(c.classList.add("status"),setTimeout(function(){c.classList.remove("status")},300));c.classList.toggle("show")},"go-up":function(){btf.scrollToDest(0,
            500)},"hide-aside-btn":function(){var b=document.documentElement.classList,c=b.contains("hide-aside")?"show":"hide";saveToLocal.set("aside-status",c,2);b.toggle("hide-aside")},"mobile-toc-button":function(b){var c=document.getElementById("card-toc");c.style.transition="transform 0.3s ease-in-out";c.classList.toggle("open");c.addEventListener("transitionend",function(){c.style.transition=""},{once:!0})},"chat-btn":function(){window.chatBtnFn()},translateLink:function(){window.translateFn.translatePage()}};
    document.getElementById("rightside").addEventListener("click",function(b){if((b=b.target.closest("[id]"))&&I[b.id])I[b.id](this)});var P=function(){document.querySelector("#sidebar-menus .menus_items").addEventListener("click",function(b){(b=b.target.closest(".site-page.group"))&&b.classList.toggle("hide")})},Q=function(){btf.addEventListenerPjax(document.getElementById("toggle-menu"),"click",function(){t.open()})},R=function(){var b=GLOBAL_CONFIG.copyright,c=b.limitCount,e=b.languages;document.body.addEventListener("copy",
        function(m){m.preventDefault();var h=window.getSelection(0).toString(),n=h;h.length>c&&(n=h+"\n\n\n"+e.author+"\n"+e.link+window.location.href+"\n"+e.source+"\n"+e.info);return m.clipboardData?m.clipboardData.setData("text",n):window.clipboardData.setData("text",n)})},S=function(){var b=document.querySelectorAll("#article-container table");b.length&&b.forEach(function(c){c.closest(".highlight")||btf.wrap(c,"div",{"class":"table-wrap"})})},T=function(){var b=document.querySelectorAll("#article-container .hide-button");
        if(b.length){var c=function(e){this.classList.add("open");e=this.nextElementSibling.querySelectorAll(".gallery-container");e.length&&F(e)};b.forEach(function(e){e.addEventListener("click",c,{once:!0})})}},U=function(){var b=document.querySelectorAll("#article-container .tabs");if(b.length){var c=function(h,n){Array.from(h).forEach(function(g){g.classList.remove("active");g!==n&&g.id!==n||g.classList.add("active")})},e=function(h,n){btf.addEventListenerPjax(h.firstElementChild,"click",function(g){g=
        g.target.closest("button");if(!g.classList.contains("active")){c(this.children,g);this.classList.remove("no-default");g=g.getAttribute("data-href");var x=this.nextElementSibling;c(x.children,g);n&&(btf.removeGlobalFnEvent("igOfTabs",this),g=x.querySelectorAll(":scope > #"+g+" .gallery-container"),g.length&&F(g,this))}})},m=function(h){btf.addEventListenerPjax(h.lastElementChild,"click",function(n){n.target.closest("button")&&btf.scrollToDest(btf.getEleTop(h),300)})};b.forEach(function(h){var n=!!h.querySelectorAll(".gallery-container");
        e(h,n);m(h)})}},V=function(){var b=document.querySelector("#aside-cat-list.expandBtn");b&&btf.addEventListenerPjax(b,"click",function(c){var e=c.target;"I"===e.nodeName&&(c.preventDefault(),e.parentNode.classList.toggle("expand"))},!0)},W=function(){var b=document.getElementById("switch-btn");if(b){var c=!1,e=document.getElementById("post-comment");btf.addEventListenerPjax(b,"click",function(){e.classList.toggle("move");c||"function"!==typeof loadOtherComment||(c=!0,loadOtherComment())})}},J=function(b){b.forEach(function(c){var e=
        c.getAttribute("datetime");c.textContent=btf.diffDate(e,!0);c.style.display="inline"})};window.refreshFn=function(){l(!0);d.classList.add("show");if(GLOBAL_CONFIG_SITE.isPost){if(void 0!==GLOBAL_CONFIG.noticeOutdate){var b=GLOBAL_CONFIG.noticeOutdate,c=b.limitDay,e=b.messagePrev,m=b.messageNext;b=b.position;var h=btf.diffDate(GLOBAL_CONFIG_SITE.postUpdate);h>=c&&(c=document.createElement("div"),c.className="post-outdate-notice",c.textContent=e+" "+h+" "+m,e=document.getElementById("article-container"),
        "top"===b?e.insertBefore(c,e.firstChild):e.appendChild(c))}GLOBAL_CONFIG.relativeDate.post&&J(document.querySelectorAll("#post-meta time"))}else{GLOBAL_CONFIG.relativeDate.homepage&&J(document.querySelectorAll("#recent-posts time"));GLOBAL_CONFIG.runtime&&(e=document.getElementById("runtimeshow"))&&(m=e.getAttribute("data-publishDate"),e.textContent=btf.diffDate(m)+" "+GLOBAL_CONFIG.runtime);if(e=document.getElementById("last-push-date"))m=e.getAttribute("data-lastPushDate"),e.textContent=btf.diffDate(m,
        !0);V()}O();GLOBAL_CONFIG_SITE.isHome&&C();D();GLOBAL_CONFIG.isPhotoFigcaption&&K();N();btf.removeGlobalFnEvent("justifiedGallery");e=document.querySelectorAll("#article-container .gallery-container");e.length&&F(e);btf.loadLightbox(document.querySelectorAll("#article-container img:not(.no-lightbox)"));S();T();U();W();Q()};refreshFn();(function(){window.addEventListener("resize",function(){l(!1);f&&btf.isHidden(document.getElementById("toggle-menu"))&&t.close()});document.getElementById("menu-mask").addEventListener("click",
        function(b){t.close()});P();GLOBAL_CONFIG.islazyload&&(window.lazyLoadInstance=new LazyLoad({elements_selector:"img",threshold:0,data_src:"lazy-src"}));void 0!==GLOBAL_CONFIG.copyright&&R();GLOBAL_CONFIG.autoDarkmode&&window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change",function(b){void 0===saveToLocal.get("theme")&&(b.matches?G("dark"):G("light"))})})()});