var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return $jscomp.arrayIterator(a);throw Error(String(a)+" is not an iterable or ArrayLike");};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
$jscomp.getRestArguments=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};
var btf={debounce:function(a,b,c){b=void 0===b?0:b;c=void 0===c?!1:c;var d;return function(){var e=$jscomp.getRestArguments.apply(0,arguments),f=c&&!d;clearTimeout(d);d=setTimeout(function(){d=null;c||a.apply(null,$jscomp.arrayFromIterable(e))},b);f&&a.apply(null,$jscomp.arrayFromIterable(e))}},throttle:function(a,b,c){var d=this;c=void 0===c?{}:c;var e,f,g,h=0,m=function(){h=!1===c.leading?0:(new Date).getTime();e=null;a.apply(f,g);e||(f=g=null)};return function(){var n=$jscomp.getRestArguments.apply(0,
        arguments),k=(new Date).getTime();h||!1!==c.leading||(h=k);var l=b-(k-h);f=d;g=n;0>=l||l>b?(e&&(clearTimeout(e),e=null),h=k,a.apply(f,g),e||(f=g=null)):e||!1===c.trailing||(e=setTimeout(m,l))}},sidebarPaddingR:function(){var a=window.innerWidth,b=document.body.clientWidth;a!==b&&(document.body.style.paddingRight=a-b+"px")},snackbarShow:function(a,b,c){b=void 0===b?!1:b;c=void 0===c?2E3:c;var d=GLOBAL_CONFIG.Snackbar,e=d.position,f=d.bgLight;d=d.bgDark;f="light"===document.documentElement.getAttribute("data-theme")?
        f:d;Snackbar.show({text:a,backgroundColor:f,showAction:b,duration:c,pos:e,customClass:"snackbar-css"})},diffDate:function(a,b){b=void 0===b?!1:b;var c=new Date(a),d=(new Date).getTime()-c.getTime(),e=GLOBAL_CONFIG.dateSuffix;if(!b)return parseInt(d/864E5);var f=d/2592E6,g=d/864E5,h=d/36E5;d/=6E4;return 12<f?c.toISOString().slice(0,10):1<=f?parseInt(f)+" "+e.month:1<=g?parseInt(g)+" "+e.day:1<=h?parseInt(h)+" "+e.hour:1<=d?parseInt(d)+" "+e.min:e.just},loadComment:function(a,b){if("IntersectionObserver"in
        window){var c=new IntersectionObserver(function(d){d[0].isIntersecting&&(b(),c.disconnect())},{threshold:[0]});c.observe(a)}else b()},scrollToDest:function(a,b){b=void 0===b?500:b;var c=window.pageYOffset,d=document.getElementById("page-header").classList.contains("fixed");if(c>a||d)a-=70;if("scrollBehavior"in document.documentElement.style)window.scrollTo({top:a,behavior:"smooth"});else{var e=null;a=+a;window.requestAnimationFrame(function h(g){e=e?e:g;g-=e;c<a?window.scrollTo(0,(a-c)*g/b+c):window.scrollTo(0,
        c-(c-a)*g/b);g<b?window.requestAnimationFrame(h):window.scrollTo(0,a)})}},animateIn:function(a,b){a.style.display="block";a.style.animation=b},animateOut:function(a,b){a.addEventListener("animationend",function d(){a.style.display="";a.style.animation="";a.removeEventListener("animationend",d)});a.style.animation=b},wrap:function(a,b,c){b=document.createElement(b);c=$jscomp.makeIterator(Object.entries(c));for(var d=c.next();!d.done;d=c.next()){var e=$jscomp.makeIterator(d.value);d=e.next().value;
        e=e.next().value;b.setAttribute(d,e)}a.parentNode.insertBefore(b,a);b.appendChild(a)},isHidden:function(a){return 0===a.offsetHeight&&0===a.offsetWidth},getEleTop:function(a){var b=a.offsetTop;for(a=a.offsetParent;null!==a;)b+=a.offsetTop,a=a.offsetParent;return b},loadLightbox:function(a){var b=GLOBAL_CONFIG.lightbox;"mediumZoom"===b&&mediumZoom(a,{background:"var(--zoom-bg)"});"fancybox"===b&&(Array.from(a).forEach(function(c){if("A"!==c.parentNode.tagName){var d=c.dataset.lazySrc||c.src;btf.wrap(c,
        "a",{href:d,"data-fancybox":"gallery","data-caption":c.title||c.alt||"","data-thumb":d})}}),window.fancyboxRun||(Fancybox.bind("[data-fancybox]",{Hash:!1,Thumbs:{showOnStart:!1},Images:{Panzoom:{maxScale:4}},Carousel:{transition:"slide"},Toolbar:{display:{left:["infobar"],middle:"zoomIn zoomOut toggle1to1 rotateCCW rotateCW flipX flipY".split(" "),right:["slideshow","thumbs","close"]}}}),window.fancyboxRun=!0))},setLoading:{add:function(a){a.insertAdjacentHTML("afterend",'\n        <div class="loading-container">\n          <div class="loading-item">\n            <div></div><div></div><div></div><div></div><div></div>\n          </div>\n        </div>\n      ')},
        remove:function(a){a.nextElementSibling.remove()}},updateAnchor:function(a){if(a!==window.location.hash){a||(a=location.pathname);var b=GLOBAL_CONFIG_SITE.title;window.history.replaceState({url:location.href,title:b},b,a)}},getScrollPercent:function(a,b){var c=b.clientHeight,d=document.documentElement.clientHeight;c=Math.round((a-b.offsetTop)/(c>d?c-d:document.documentElement.scrollHeight-d)*100);return 100<c?100:0>=c?0:c},addGlobalFn:function(a,b,c,d){c=void 0===c?!1:c;d=void 0===d?window:d;var e=
        d.globalFn||{},f=e[a]||{};c&&f[c]||(c=c||Object.keys(f).length,f[c]=b,e[a]=f,d.globalFn=e)},addEventListenerPjax:function(a,b,c,d){d=void 0===d?!1:d;a.addEventListener(b,c,d);btf.addGlobalFn("pjax",function(){a.removeEventListener(b,c,d)})},removeGlobalFnEvent:function(a,b){var c=b=void 0===b?window:b,d=(void 0===c.globalFn?{}:c.globalFn)[a]||{};c=Object.keys(d);c.length&&(c.forEach(function(e){d[e]()}),delete b.globalFn[a])}};